# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Install Python 3.6
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
        shell: bash
      - name: Run nox
        run: |
          python -m nox --error-on-missing-interpreters -s lint
        shell: bash
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] #, Windows, macOS]
        python_version:
          ["3.6", "3.7", "3.8", "3.9"]
        # exclude:
        #   # This is failing due to shapely not being packaged for python3.9 on macOS.
        #   # https://github.com/Toblerity/Shapely/issues/1040
        #   - os: macOS
        #     python_version: 3.9
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          sudo apt-get install cmake build-essential libjpeg-dev libpng-dev libturbojpeg
          python -m pip install --upgrade pip
          python -m pip install nox
        shell: bash
      - name: Run nox
        run: |
          python -m nox --error-on-missing-interpreters -s tests-${{ matrix.python_version }}
        shell: bash
